

Project:{
    
    
    """ 멤버쉽 테이블 """
    member:{
        shape:sql_table
        
        user_no:int{constraint:primary_key}
        buy_list:varchar2(100)
        buy_sum:int
        user_grade:varchar2(20)
        member_ticket:varchar2(20){constraint:foreign_key}
        member_goods:varchar2(20){constraint:foreign_key}
        
        
    }
    
    """ 회원 테이블 """
    user:{
        shape:sql_table
        
        user_no:varchar2(10){constraint:primary_key}
        user_id:varchar2(20){constraint:unique}
        user_pwd:varchar2(20)
        user_name:varchar2(20)
        user_phone:varchar2(20){constraint:unique}
        user_age:varchar2(20){constraint:not null}
        user_gender:varchar2(10){constraint:not null}
        user_email:varchar2(30){constraint:not null}
        user_addr:varchar2(100){constraint:not null}
        user_key:varchar2(14){constraint:unique}

    }
    order_ticket:{
        shape:sql_table

        user_no:int{constraint:primary_key}
        member_ticket:varchar2(20){constraint:foreign_key}
    }
    order_goods:{
        shape:sql_table

        user_no:int{constraint:primary_key}
        member_goods:varchar2(20){constraint:foreign_key}
        goods_no:int
    }
    goods{
        shape:sql_table
        goods_no:int{constraint:primary_key}
    }
    user.user_no <-> member.user_no : user_no
    user.user_no <-> order_ticket.user_no : user_no
    user.user_no <-> order_goods.user_no : user_no

    member.member_goods <-> order_goods.member_goods :member_goods
    member.member_ticket <-> order_ticket.member_ticket : member.ticket

    order_goods.goods_no <-> goods.goods_no :goods_no
    
}