
PROJECT:{

    MEMBER:{
        
        
        """ 멤버쉽 테이블 """
    member:{
        shape:sql_table
        
        user_no:int{constraint:primary_key}
        buy_list:varchar2(100)
        buy_sum:int
        user_grade:varchar2(20)
        member_ticket:varchar2(20){constraint:foreign_key}
        member_goods:varchar2(20){constraint:foreign_key}
        
        
    }
    
    """ 회원 테이블 """
    user:{
        shape:sql_table
        
        user_no:varchar2(10){constraint:primary_key}
        user_id:varchar2(20){constraint:unique}
        user_pwd:varchar2(20)
        user_name:varchar2(20)
        user_phone:varchar2(20){constraint:unique}
        user_age:varchar2(20){constraint:not null}
        user_gender:varchar2(10){constraint:not null}
        user_email:varchar2(30){constraint:not null}
        user_addr:varchar2(100){constraint:not null}
        user_key:varchar2(14){constraint:unique}
        
    }
}
ORDER:{

    TICKET:{
        
        order_ticket:{
            shape:sql_table
            
            user_no:int{constraint:primary_key}
            member_ticket:varchar2(20){constraint:foreign_key}
            ticket_no:int
        }
        ticket:{
            shape:sql_table
            ticket_no:int{constraint:primary_key}

        }
    }
    GOODS:{
        
        order_goods:{
            shape:sql_table
            
            user_no:int{constraint:primary_key}
            member_goods:varchar2(20){constraint:foreign_key}
            goods_no:int
        }
        goods{
            shape:sql_table
            goods_no:int{constraint:primary_key}
        }
    }
}
BOARD:{
    board:{
        shape:sql_table
        board_no:int
        qna:varchar2(200)
        notice:varchar2(200)

    }
}
MEMBER.member.user_no <-> MEMBER.user.user_no

MEMBER.member.user_no <->ORDER.TICKET.order_ticket.user_no
MEMBER.member.user_no <->ORDER.GOODS.order_goods.user_no


}
